Repository schubergphilis/terraform-azure-mcaf-key-vault, pull requests merged in 2024-11, with the labels that each got.

#2 misc: fix some naming inconsistencies
  README.md
  examples/basic/main.tf
  main.tf
  outputs.tf
  tests/basic.tftest.hcl
  variables.tf
Labels: bug

#4 feat: adding public_network_access_enabled as well
  README.md
  examples/basic/main.tf
  main.tf
  variables.tf
Labels: feature

#5 enhancement: Update outputs.tf
  README.md
  outputs.tf
Labels: enhancement, feature
