Repository schubergphilis/terraform-azure-mcaf-key-vault, pull requests merged in 2025-04, with the labels that each got.

#11 breaking: add private endpoints, role assignments, move vars to top level
  .gitignore
  .terraform.lock.hcl
  README.md
  examples/basic/main.tf
  locals.tf
  main.private_endpoints.tf
  main.tf
  variables.private_endpoints.tf
  variables.tf
Labels: feature, breaking

#12 fix: better check for private endpoints
  locals.tf
  main.private_endpoints.tf
Labels: bug

#13 feat: make var for cmk key size
  README.md
  main.tf
  variables.tf
Labels: feature

#14 fix: switch to maps
  README.md
  examples/basic/main.tf
  locals.tf
  main.tf
  variables.tf
Labels: bug

#15 feat: add cmk_time_before_expiry variable
  README.md
  examples/basic/main.tf
  main.tf
  migrations.tf
  outputs.tf
  variables.tf
Labels: feature

#16 fix: shift key rotation policy
  README.md
  main.tf
  variables.tf
Labels: bug

#18 fix: Correct the role name
  locals.tf
Labels: fix
